{{- if and .Values.workspace.storageClass (not (empty .Values.workspace.storageClass)) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ravenclaw.fullname" . }}-workspace
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ravenclaw.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.workspace.storageClass }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
{{- end }}
