{{- if .Values.secrets | keys | len | gt 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ravenclaw.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ravenclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
